### ISSUE TITLE
iommu configuration not enable in kernel when driver is uio_pci_generic 

### ISSUE THREAD

**Issue by Kimido90** [Juniper/contrail-tripleo-heat-templates#117]
the ansible script which is setting the kernel args configuration doesn't set correctly the kernle iommu arg when driver is uio_pci_generic.

templates/extraconfig/pre_network/contrail/contrail_ansible_kernel_config.yaml
 tasks:
    # Kernel Args Configuration
    - name: init kernel arg list
      set_fact:
        kernel_arg_list: []
    - name: set kernel iommu arg
      set_fact:
        kernel_arg_list: "{{ kernel_arg_list }} + [ 'iommu=pt' ]"
      when: (_**CONTRAIL_DPDK_DRIVER_ is defined and _CONTRAIL_DPDK_DRIVER_ == "vfio-pci"**) or (_CONTRAIL_SRIOV_NUM_VFS_ is defined and _CONTRAIL_SRIOV_NUM_VFS_ != '')
    - name: set kernel intel_iommu arg
      set_fact:
        kernel_arg_list: "{{ kernel_arg_list }} + [ 'intel_iommu=on' ]"
      when: (_**CONTRAIL_DPDK_DRIVER_ is defined and _CONTRAIL_DPDK_DRIVER_ == "vfio-pci**") or (_CONTRAIL_SRIOV_NUM_VFS_ is defined and _CONTRAIL_SRIOV_NUM_VFS_ != '')

we need to add a condition for driver  type uio_pci_generic.

**Comment by alexey-mr** [comment]
it looks resolved, please, let know if not.
