### ISSUE TITLE
Internal-TLS-enabled RHOSP13z7 + Contrail 5.X deploy fails on missing krb-service-principals.yaml file

### ISSUE THREAD

**Issue by 9strands** [Juniper/contrail-tripleo-heat-templates#119]
https://github.com/Juniper/contrail-tripleo-heat-templates/blob/49ffa60589c76be29bc52f2fba8593cbb24eb5b9/environments/contrail/contrail-tls.yaml#L6

In the RHOSP13 (queens) z7 openstack-tripleo-heat-templates, the referenced 
`<templates>nova_metadata/krb-service-principals.yaml`
no longer exists.

It has been replaced by a directory `<templates>/extraconfig/krb-servicep-principals/` with a j2 template which is rendered using the format `<role>-role.j2.yaml` per each role defined in roles_data.yaml and creates multiple files as per the following 

```<templates>/extraconfig/nova_metadata/krb-service-principals/
| - compute-role.yaml
| - controller-role.yaml
| - contrailaio-role.yaml
```

The contrail-tls.yaml machines will need to account for this altered composeable-role-based function in order to work correctly with the new templates for RHOSP13 (queens)

**Comment by 9strands** [comment]
It appears that someone has been working on this issue with commit dfc5db71a0af71aea69e55b7873f57f0cc3acc43

**Comment by alexey-mr** [comment]
yes. thar fix should close this issue.
